baseURL = "https://gamerita14.github.io"
languageCode = "it-IT"
title = "L' Angolo Del Dolce"
theme = "ananke"
DefaultContentLanguage = "it"


[params]
  background_color_class = "bg-light-red"
  facebook="https://www.facebook.com/gorga.carmine"
  contatti="/post/contatti"
  featured_image = "/Immagini/logo.jpg"
  recent_posts_number = 2